# Generated by Django 4.1.5 on 2023-01-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_photo',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
