# Generated by Django 4.1.5 on 2023-01-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_pet_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type_needs_care',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
