# Generated by Django 4.1.5 on 2023-01-27 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petsitters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_type_needs_care', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bird', 'Bird'), ('other', 'Other')], default='other', max_length=50)),
                ('pet_needs_description', models.CharField(blank=True, max_length=200)),
                ('is_needs_care', models.BooleanField(default=False)),
                ('pet_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('petsitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsitters.petsitter')),
            ],
        ),
    ]
