# Generated by Django 4.1.5 on 2023-02-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_pet_type_needs_care'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_photo',
        ),
    ]
