# Generated by Django 4.1.5 on 2023-01-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsitter',
            old_name='pet_type',
            new_name='pet_type_take_care',
        ),
    ]
