# Generated by Django 4.1.5 on 2023-01-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0007_alter_petsitter_photo_petsitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitter',
            name='photo_petsitter',
            field=models.ImageField(blank=True, default='/images/blank-profile-picture.jpg', null=True, upload_to='images/'),
        ),
    ]
