# Generated by Django 4.1.5 on 2023-01-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsitters', '0003_petsitter_is_looking_for_help_petsitter_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsitter',
            name='photo_petsitter',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
